# -*- coding: utf-8 -*-
"""Openin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KCFEBbJQ1t3mzcLDZ9y3xM5DdNkdzxub
"""

pip install gTTs

from IPython.display import Audio

# Import the gTTS module for text
# to speech conversion
from gtts import gTTS

# Input a text value that we want to convert to audio
text_val = input("Enter Text: ")

# Here are converting in English Language
language = 'en'

# Passing the text and language to the engine,
# here we have assign slow=False. Which denotes
# the module that the transformed audio should
# have a high speed
obj = gTTS(text=text_val, lang=language, slow=False)

#Here we are saving the transformed audio in a mp3 file named
# exam.mp3
obj.save("final.mp3")

# Play the exam.mp3 file
Audio("/content/final.mp3")
#playsound("exam.mp3")